Web3 config for actions
mimic-fi/v2-frontend pull request #63
Opened 2023-05-10 19:55 UTC by delfipolito

2023-05-12 17:22 UTC, brunitob requested changes
🤝

2023-05-12 17:22 UTC, brunitob commented on src/sections/Function.js
use more descriptive name, maybe something like:

- displayFunction
- renderFunction

2023-05-12 17:22 UTC, brunitob commented on src/sections/MoreActions.js
>    //TODO: remove two hardcoded items and replace them for real data
```suggestion
```

2023-05-12 17:22 UTC, brunitob commented on src/utils/web3-utils.js
> +  const gwei = wei / 1000000000
```suggestion
  if (!wei) return 0
  const gwei = wei / 1000000000
```

2023-05-16 21:37 UTC, delfipolito commented on src/sections/Function.js
How about ConfigParam?

2023-05-17 18:24 UTC, brunitob approved these changes
🎉 huge milestone

2023-05-17 19:21 UTC, merged